/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetEthMarketplaceTraitDataRequest {
    /// The contract address of the collection.
    #[serde(rename = "collection_address")]
    pub collection_address: String,
}

impl GetEthMarketplaceTraitDataRequest {
    pub fn new(collection_address: String) -> GetEthMarketplaceTraitDataRequest {
        GetEthMarketplaceTraitDataRequest {
            collection_address,
        }
    }
}


