/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetEthWalletLabelsRequest {
    /// The EVM compatible wallet address
    #[serde(rename = "wallet_address")]
    pub wallet_address: String,
}

impl GetEthWalletLabelsRequest {
    pub fn new(wallet_address: String) -> GetEthWalletLabelsRequest {
        GetEthWalletLabelsRequest {
            wallet_address,
        }
    }
}


