/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetSolHistoricalTransactionsRequest {
    /// The Gallop slug for the collection. Please see sol/getCollections endpoint.
    #[serde(rename = "collection_tag")]
    pub collection_tag: String,
    /// The pagination cursor.
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<i32>,
}

impl GetSolHistoricalTransactionsRequest {
    pub fn new(collection_tag: String) -> GetSolHistoricalTransactionsRequest {
        GetSolHistoricalTransactionsRequest {
            collection_tag,
            page: None,
        }
    }
}


