/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetEthHistoricalEventsRequest {
    /// The contract address of a collection.
    #[serde(rename = "collection_address")]
    pub collection_address: String,
    /// The id for the token.
    #[serde(rename = "token_id", skip_serializing_if = "Option::is_none")]
    pub token_id: Option<String>,
    /// The pagination cursor.
    #[serde(rename = "page", skip_serializing_if = "Option::is_none")]
    pub page: Option<i32>,
    /// The number of records returned per page.
    #[serde(rename = "page_size", skip_serializing_if = "Option::is_none")]
    pub page_size: Option<PageSize>,
    /// The type of event: list, transfer, offer, mint, sale, cancel_list or cancel_offer
    #[serde(rename = "event_type", skip_serializing_if = "Option::is_none")]
    pub event_type: Option<EventType>,
}

impl GetEthHistoricalEventsRequest {
    pub fn new(collection_address: String) -> GetEthHistoricalEventsRequest {
        GetEthHistoricalEventsRequest {
            collection_address,
            token_id: None,
            page: None,
            page_size: None,
            event_type: None,
        }
    }
}

/// The number of records returned per page.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PageSize {
    #[serde(rename = "50")]
    Variant50,
    #[serde(rename = "100")]
    Variant100,
    #[serde(rename = "500")]
    Variant500,
    #[serde(rename = "1000")]
    Variant1000,
}

impl Default for PageSize {
    fn default() -> PageSize {
        Self::Variant50
    }
}
/// The type of event: list, transfer, offer, mint, sale, cancel_list or cancel_offer
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum EventType {
    #[serde(rename = "list")]
    List,
    #[serde(rename = "transfer")]
    Transfer,
    #[serde(rename = "offer")]
    Offer,
    #[serde(rename = "mint")]
    Mint,
    #[serde(rename = "sale")]
    Sale,
    #[serde(rename = "cancel_list")]
    CancelList,
    #[serde(rename = "cancel_offer")]
    CancelOffer,
}

impl Default for EventType {
    fn default() -> EventType {
        Self::List
    }
}

