/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetSolRarityRequest {
    /// The Gallop tag for the Solana collection. Please see sol/getCollections endpoint.
    #[serde(rename = "collection_tag")]
    pub collection_tag: String,
    /// A list of token addresses.
    #[serde(rename = "mint_address", skip_serializing_if = "Option::is_none")]
    pub mint_address: Option<Vec<String>>,
    /// Dict containing trait keys and weight values.
    #[serde(rename = "weights", skip_serializing_if = "Option::is_none")]
    pub weights: Option<serde_json::Value>,
}

impl GetSolRarityRequest {
    pub fn new(collection_tag: String) -> GetSolRarityRequest {
        GetSolRarityRequest {
            collection_tag,
            mint_address: None,
            weights: None,
        }
    }
}


