/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetEthMarketplaceDataRequest {
    /// Array of collection addresses
    #[serde(rename = "collection_address")]
    pub collection_address: Vec<String>,
    /// Array of sub collections (e.g. Art Blocks)
    #[serde(rename = "sub_collection_tags", skip_serializing_if = "Option::is_none")]
    pub sub_collection_tags: Option<Vec<String>>,
}

impl GetEthMarketplaceDataRequest {
    pub fn new(collection_address: Vec<String>) -> GetEthMarketplaceDataRequest {
        GetEthMarketplaceDataRequest {
            collection_address,
            sub_collection_tags: None,
        }
    }
}


