/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetPolMarketplaceDataRequest {
    /// Array of collection addresses
    #[serde(rename = "collection_address")]
    pub collection_address: Vec<String>,
}

impl GetPolMarketplaceDataRequest {
    pub fn new(collection_address: Vec<String>) -> GetPolMarketplaceDataRequest {
        GetPolMarketplaceDataRequest {
            collection_address,
        }
    }
}


