/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetEthCollectionListingsOhlcRequest {
    /// The Ethereum contract address to identify the collection.
    #[serde(rename = "collection_address")]
    pub collection_address: String,
    /// The interval at which to return OHLC, e.g. `1D` for daily, `1M` for monthly etc.
    #[serde(rename = "frequency", skip_serializing_if = "Option::is_none")]
    pub frequency: Option<String>,
    /// The currency to report results in
    #[serde(rename = "rept_curr", skip_serializing_if = "Option::is_none")]
    pub rept_curr: Option<ReptCurr>,
    /// The ISO 8601 date/datetime of the oldest listing to pull for calculations
    #[serde(rename = "listing_start_date", skip_serializing_if = "Option::is_none")]
    pub listing_start_date: Option<String>,
    /// The ISO 8601 date/datetime of the most recent listing to pull for calculations
    #[serde(rename = "listing_end_date", skip_serializing_if = "Option::is_none")]
    pub listing_end_date: Option<String>,
    /// The ISO 8601 start date/datetime to return results for
    #[serde(rename = "report_start_date", skip_serializing_if = "Option::is_none")]
    pub report_start_date: Option<String>,
    /// The ISO 8601 end date/datetime to return results for
    #[serde(rename = "report_end_date", skip_serializing_if = "Option::is_none")]
    pub report_end_date: Option<String>,
}

impl GetEthCollectionListingsOhlcRequest {
    pub fn new(collection_address: String) -> GetEthCollectionListingsOhlcRequest {
        GetEthCollectionListingsOhlcRequest {
            collection_address,
            frequency: None,
            rept_curr: None,
            listing_start_date: None,
            listing_end_date: None,
            report_start_date: None,
            report_end_date: None,
        }
    }
}

/// The currency to report results in
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReptCurr {
    #[serde(rename = "eth")]
    Eth,
    #[serde(rename = "usd")]
    Usd,
}

impl Default for ReptCurr {
    fn default() -> ReptCurr {
        Self::Eth
    }
}

