/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetSolNftAccountRequest {
    /// The Solana token mint address.
    #[serde(rename = "mint_address")]
    pub mint_address: String,
}

impl GetSolNftAccountRequest {
    pub fn new(mint_address: String) -> GetSolNftAccountRequest {
        GetSolNftAccountRequest {
            mint_address,
        }
    }
}


