/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetSolAccountNftsRequest {
    /// The account address to query.
    #[serde(rename = "account_address")]
    pub account_address: String,
}

impl GetSolAccountNftsRequest {
    pub fn new(account_address: String) -> GetSolAccountNftsRequest {
        GetSolAccountNftsRequest {
            account_address,
        }
    }
}


