/*
 * Gallop API
 *
 * Data and insights APIs, webooks, and dashboards enabling businesses to launch tokenized products in seconds.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@higallop.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetPolRarityRequest {
    /// The Polygon contract address to identify the collection.
    #[serde(rename = "collection_address")]
    pub collection_address: String,
    /// Dict containing trait keys and weight values.
    #[serde(rename = "weights", skip_serializing_if = "Option::is_none")]
    pub weights: Option<serde_json::Value>,
    /// An array of token ids.
    #[serde(rename = "token_id", skip_serializing_if = "Option::is_none")]
    pub token_id: Option<Vec<String>>,
}

impl GetPolRarityRequest {
    pub fn new(collection_address: String) -> GetPolRarityRequest {
        GetPolRarityRequest {
            collection_address,
            weights: None,
            token_id: None,
        }
    }
}


